### ISSUE TITLE
Cannot find module './types' or its corresponding type declarations.

### ISSUE THREAD

**Issue by naamapps** [NftEyez/sol-rayz#15]
Hey,
I installed and tried to use this package on Angular.
I get this error on build.

Please advice,
Thanks

```

Error: node_modules/@nfteyez/sol-rayz/dist/config/metaplex.d.ts:1:33 - error TS2307: Cannot find module '../types' or its corresponding type declarations.

1 import { StringPublicKey } from "../types";
                                  ~~~~~~~~~~


Error: node_modules/@nfteyez/sol-rayz/dist/getParsedAccountByMint.d.ts:2:33 - error TS2307: Cannot find module './types' or its corresponding type declarations.

2 import { StringPublicKey } from "./types";
                                  ~~~~~~~~~


Error: node_modules/@nfteyez/sol-rayz/dist/getParsedNftAccountsByOwner.d.ts:2:33 - error TS2307: Cannot find module './types' or its corresponding type declarations.

2 import { StringPublicKey } from "./types";
                                  ~~~~~~~~~


Error: node_modules/@nfteyez/sol-rayz/dist/resolveToWalletAddress.d.ts:2:33 - error TS2307: Cannot find module './types' or its corresponding type declarations.

2 import { StringPublicKey } from "./types";
                                  ~~~~~~~~~




✖ Failed to compile.

```

**Comment by jamland** [comment]
hey @naamapps !
I think it is not related to Angular. it should be agnostic to the js framework.
it might be related to your js bundler, like Webpack or whatever you use. and how things are transpiled/compiled in your project.

I've created Angular codesandbox. It seems to work well. check it here:
https://codesandbox.io/s/heuristic-fermi-b1vi6?file=/src/app/app.component.ts

**Comment by marcsabate7** [comment]
Hi, im having some problems in the deployment. I just add all the files in my src folder. And show me this error. How i have to call the function useWalletNfts?? You have any code example please!!
Thanks for this!
Could not load source file "../src/index.ts" in source map of "../node_modules/@nfteyez/sol-rayz-react/dist/index.js" (think that is fixed for now)
Here i have an image where im executing the tsx code. What i have to do after this..? first time using react.
The counter is only the filename, im arriving at the console.log("here"); But at the console.log thow me error about hook.
![image](https://user-images.githubusercontent.com/64595179/151607684-76da735f-c2f0-4fc4-a3a1-1fc1bc134012.png)
![image](https://user-images.githubusercontent.com/64595179/151607735-c0eff117-3ac0-422d-9067-ac09c2674e4a.png)

**Comment by jamland** [comment]
hey @marcsabate7 
I've updated README with proper example:
https://github.com/NftEyez/sol-rayz/blob/main/packages/sol-rayz-react/README.md

1st of all these are React Hooks and can't be used with classes only with functional components. Google the difference. e.g. 
https://dev.to/mehmehmehlol/class-components-vs-functional-components-in-react-4hd3

Also, here is more detailed example on how to fetch wallet NFTs with this hook:
https://github.com/thuglabs/create-dapp-solana-nextjs/blob/main/src/views/GalleryView/index.tsx

**Comment by joshuajaco** [comment]
I'm also running into this issue. 
The error comes from typescript when setting [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck) to false. The issue is that the referenced file `../types` does not exist in the bundle. 

![image](https://user-images.githubusercontent.com/31038284/154127572-b1208324-2712-4184-a4ed-f164df5982a2.png)
