### ISSUE TITLE
Support for new solana metadata spec

### ISSUE THREAD

**Issue by dino-rodriguez** [NftEyez/sol-rayz#18]
It seems there are a few new metadata fields for the onchain metadata spec for solana NFTs: https://docs.metaplex.com/token-metadata/specification

e.g. collection

Are you guys going to add support for these metadata fields?

**Comment by jamland** [comment]
yeah, good point @dino-rodriguez.

For now, we just pass all content from metadata account to the user of `getParsedNftAccountsByOwner` fn.
We only doing some cleaning, sanitizing, sorting, prettifying actions.
So, any changes in Metadata Standard should not affect how the fn works. Anyway, I need to test it with some collections created with the new standards to be sure.

Another tool I was thinking about recently is the method to return all info about collection based on this updated  Metadata Standard. This is obviously extremely useful to have

**Comment by dino-rodriguez** [comment]
Got it. When I did this manually and decoded the data using the `Metaplex` js library to decode, it decodes to include `collection` (even if its undefined because its an NFT on the old standard). My main question is - is the collection field present for NFTs fetched with the new standard? I don't have any NFTs on the new standard.

I think that tool you mentioned would also be really useful!

**Comment by jamland** [comment]
interesting. need to check how they do it.
I will try to mint some collection with Candy Machine v.2 and see how it works
