### ISSUE TITLE
Support getParsedAccountByMint in react library

### ISSUE THREAD

**Issue by dino-rodriguez** [NftEyez/sol-rayz#20]
Currently it looks like only get accounts by owner / wallet is supported. Is this indeed the case? Are there plans to also have a hook for the `getParsedAccountByMint`?

**Comment by jamland** [comment]
Yes, for now only this hook is implemented as the most frequently used functionality.

If you wish you can quickly recreate such hook for `getParsedAccountByMint` just copy-pasting code from this file 👉

https://github.com/NftEyez/sol-rayz/blob/main/packages/sol-rayz-react/src/hooks/useWalletNfts.ts

and replacing `getParsedNftAccountsByOwner` fn with `getParsedAccountByMint`. Should be easy like this 🙂

**Comment by dino-rodriguez** [comment]
Sounds good! I may put out a PR in that case :)

**Comment by jamland** [comment]
this would be awesome!
