### ISSUE TITLE
example of createConnectionConfig

### ISSUE THREAD

**Issue by rektadult** [NftEyez/sol-rayz#23]
@jamland do you have an example using/passing in the createConnectionConfig object? i am using a private rpc.

no matter how i try to pass clusterAPI into my connection functions, sol-rayz uses devnet. i definitely admit i don't understand everything, but a working example here would be very helpful.

thanks for making this, sol-rayz has helped a lot in my projects.

**Comment by VeritasV** [comment]
const { Connection } = require('@solana/web3.js');

const connection = new Connection(
  'https://your-rpc.solana-mainnet.quiknode.pro',
  'confirmed'
);

**Comment by rektadult** [comment]
thanks @VeritasV
