### ISSUE TITLE
limit is missing from useWalletNfts hook

### ISSUE THREAD

**Issue by 0xDeeep** [NftEyez/sol-rayz#28]
There is no filed as limit in this hook type 
```
export declare type Options = {
    /**
     * Wallet public address
     */
    publicAddress: StringPublicKey;
    /**
     * Optionally provide your own connection object.
     * Otherwise createConnectionConfig() will be used
     */
    connection?: Connection;
    /**
     * Remove possible rust's empty string symbols `\x00` from the values,
     * which is very common issue.
     * Default is true
     */
    sanitize?: boolean;
    /**
     * TODO: Add description within README and link here
     * Default is false - slow method
     * true - is fast method
     */
    strictNftStandard?: boolean;
    /**
     * Convert all PublicKey objects to string versions.
     * Default is true
     */
    stringifyPubKeys?: boolean;
    /**
     * Sort tokens by Update Authority (read by Collection)
     * Default is true
     */
    sort?: boolean;
};
```
Problem: 
As there is no limit constraint in it. It's currently fetching all of the nft from the wallet. 
For example, I have a wallet which has a ~10K nfts, sadly it is fetching all of them at once, making the browser stuck & hanged.

<img width="283" alt="Screenshot 2022-05-12 at 1 29 55 PM" src="https://user-images.githubusercontent.com/65382963/168022774-ba6a2506-4101-4d44-93b7-5ae4ba5fea97.png">

Q: How can I use the limit here @jamland?

**Comment by kobyle69** [comment]
It would be indeed good to use some limit and an offset

**Comment by VeritasV** [comment]
hmmm will check what cand we do
