### ISSUE TITLE
AngularJS adaptation

### ISSUE THREAD

**Issue by DloomPlz** [NftEyez/sol-rayz#31]
Hello guys !
I would like to use this library in my AngularJS App, but I cant use this one as its in TypeScript and made for React.

Does anyone knows how I can make it work? 

Would that be possible to build a vanilla JS script for it ?

Thanks :)

**Comment by VeritasV** [comment]
You can use @nfteyez/sol-rayz without React. It's a core functionality package.

**Comment by DloomPlz** [comment]
I tried to compile it so it can be used as a pure JS file but had no luck. Do you know by any chance how to compile it in pure JS ?

Thank you for your answer !
