### ISSUE TITLE
URI call got in getParsedNftAccountsByOwner creates a CORS issue

### ISSUE THREAD

**Issue by haris-aqeel** [NftEyez/sol-rayz#35]
When I make a fetch to uri through my NEXT application on frontend, most of them succeeds. The URI with domain https://ethnetworkapplied.net/info-metadata.json?q=d7cf793a0485f23457368bdc23dda8ee though opening and showing json in google chromes creates a CORS error in the application. 

I am just calling the URL to get the image. Is their any way of directly getting image if there is no solution for this CORS issue.

**Comment by haris-aqeel** [comment]
I saw my same NFTS on https://magiceden.io/me visible. What is the alternate of it?

**Comment by jamland** [comment]
I suppose you need to check some Next.js config settings to allow CORS.

> Is their any way of directly getting image if there is no solution for this CORS issue.    

Getting image URL from JSON is only way to find it.

In any way, CORS issue seems to be unrelated to this package.

**Comment by haris-aqeel** [comment]
Metaplex provides us a function mx.nfts().load({metadata}). Do you have any such function?
