### ISSUE TITLE
Returning 429 error when getting solana NFTs

### ISSUE THREAD

**Issue by henry1jin** [NftEyez/sol-rayz#37]
We're using the library the way it is used in the example in the README.md, but getting 429 errors.

**Comment by jamland** [comment]
429 error seems to be "[too many requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)"

Most likely it means Solana RPC-node is blocking your requests. 
This could be the issue if you use some default Solana mainnet-beta rpc-node. They just prevent you from abusing their node.

You might need to find alternative RPC-node URL to use.
Or if you use custom RPC-node url talk to your provider about the issue.

In any case this issue doesn't seem to be related to this package but to RPC-node settings
