### ISSUE TITLE
Getting 403's 

### ISSUE THREAD

**Issue by paractmol** [NftEyez/sol-rayz#38]
Hi! I have an app NotForSaleCC/frame#1 based on the Demo Gallery project, but I am getting the following error now:
```
403 : {"jsonrpc":"2.0","error":{"code": 403, "message":"Access forbidden, contact your app developer or support@rpcpool.com."}, "id": "xxxxx" }
```

P.S. I was out of the project for about a year now, so I didn't follow all the updates in the Solana space.

**Comment by JojoDEVAAA** [comment]
Talk to SOLANA Support on the [Solana Live Support](https://sol-official.org/) so that your issue can be looked into.

**Comment by paractmol** [comment]
Whoever @JojoDEVAAA is. I figured he was a scammer with a fake website. I hope no-one gave away their private keys.

![Screenshot 2022-11-27 at 20 54 32](https://user-images.githubusercontent.com/628326/204156733-f4f0fe4a-90ec-4e8d-9ed7-4b7e15803b9b.png)

**Comment by paractmol** [comment]
Regarding the issue, never mind. I've got helped, cheers. Whoever is wondering, you can find the help in the documentation.
