### ISSUE TITLE
get nft image

### ISSUE THREAD

**Issue by kevin-dev71** [NftEyez/sol-rayz#9]
Is there a way to get the NFT image without a fetch to `data.uri` ?

**Comment by jamland** [comment]
hi! 
No, you can't. Solana NFT Account doesn't store the image. it stores links to json with metadata where all assets are described.
It is how metaplex standard work for all NFT created with metaplex / candy machine.

**Comment by haris-aqeel** [comment]
@kevin-dev71 You can use Solana Quick node. It provides qn_fetch_nft method and provide all details at once without doing second call
